apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: enshrouded
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/apps/enshrouded
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
